team/m2/features.md, team/reports/joshua-swaida.md
I finalized the features.md file and my report file.
=> Finished features.md and my report file

team/m2/features.md, team/reports/joshua-swaida.md
I improved the feature descriptions and added a new feature (Profile settings). I updated my commit link for the finalized features.md file in my report file.
=> Made final edits to features.md and my report file.

frontend/source/components/BaseComponent/BaseComponent.js
Inside the components folder I created a BaseComponent folder and file. 
I also created an AppControllerComponent with an empty corresponding file. We can use that later to change between views.
=> Created BaseComponent and template for AppControllerComponent

frontend/source/components/AppControllerComponent/AppControllerComponent.js, frontend/source/components/EventCreationComponent/EventCreationComponent.css, frontend/source/components/EventCreationComponent/EventCreationComponent.js, frontend/source/components/HomeComponent/HomeComponent.js, frontend/source/index.html, frontend/source/main.js, frontend/source/services/MeetingRepositoryFactory.js, frontend/source/services/MeetingRepositoryRemoteFakeService.js
Implemented the event creation component that allows users to enter event details (event name, description), invite other users, and enter potential event times.
Implemented a Homepage component. When you run the program, the Homepage will initially appear in the browser and you can switch to the Event creation page by clicking a button.
Finalized the frontend project structure by adding the index.html, main.js, and main.css files. Also set up and started implementing the AppControllerComponent (I imported the EventCreationComponent and HomeComponent and made it so that you can switch between both views). 
Closes #18 
Closes #19
=> Implemented the Event creation component, Homepage component, and finalized the frontend project structure

frontend/source/components/EventCreationComponent/EventCreationComponent.css, frontend/source/components/EventCreationComponent/EventCreationComponent.js
- validated time inputs (validated start time, end time, and date format. Also made sure the inputted date is not in the past. Also made sure that  the start time is before the end time).
- made the potential times list interactive (added a delete button next to every time added)
- made the invitees list interactive (added a delete button next to every invitee added)
- ensured all input fields, the times list, and invitees list were all cleared upon clicking "create event" button
Closes #28
=> Finished implementing EventCreationComponent and it's InteractiveInviteesList and InteractiveTimesList 

frontend/source/components/HomeComponent/HomeComponent.css, frontend/source/components/HomeComponent/HomeComponent.js
- Added description of the application
- Described what each button on navigation bar does (created an unordered list)
Closes #31
=> Finished implementation of Homepage component

team/m3/m3.md, team/m3/tan-le/feature-sequence-diagram.md
Finalized UI and complete my part on m3.dmd, sequence diagram
=> Tan UI updates

frontend/source/components/EventCreationComponent/EventCreationComponent.js
Specifies (using input box placeholder text) that the user must enter time in the HH:MM 24-hour format
Specifies (using input box placeholder text) that the user must enter the date in the YYYY-MM-DD format
Closes #53
=> Clarifies EventCreation time/date input format

README.md, backend/controller/controller.js, backend/middleware/middleware.js, backend/model/Event.js, backend/model/EventParticipant.js, backend/model/Invitation.js, backend/model/User.js, backend/model/main.js, backend/package.json, backend/routes/routes.js, backend/src/app.js, team/reports/tan-le.md
I have implemented basic authentication using JWT and contain tokens in headers in HTTP request. I will ask Tim tomorrow to make sure if this is okay or we have to do something more complicated such as him.
=> Finished basic login and register routes, middleware for authentication

README.md
Added more detailed instructions for running back end with .env file in README.md
=> Added more details on .env file in documentation

backend/controller/controller.js, backend/model/Event.js, backend/model/main.js, backend/routes/routes.js, team/reports/joshua-swaida.md
- Created the /events route in routes.js to handle event creation requests. Ensured only clients with a valid JWT can make a POST request to this route. 
- Implemented the createEvent function in controller.js as the callback for the /events route.
- On successful requests, the server stores the newly created event in the Sequelize database and sends a success message to the client.
- On failed requests, the server sends a failure message to the client. 
Closes #59
=> Implemented Event Creation Route in backend

README.md, backend/controller/controller.js, backend/middleware/middleware.js, backend/package.json, backend/routes/routes.js
Finish implementing logout route on backend. Security after logging out is now ensured.
=> Finish logout route on backend

backend/controller/controller.js, backend/routes/routes.js
Finish GET and PATCH endpoint for user models
=> Finish fetching and modification backend API routes for profile settings

backend/controller/controller.js
Update createEvent callback function and handled EventParticipant creation and invitee email validation
- Processed the invitees array, ensuring it contains valid emails (checked UserInstance table).
- Returned 400 Bad Request error if any invitees weren't registered users.
- Iterated over the list of valid invitee IDs and created EventParticipantInstance records for each invitee.
- Created createEventParticipant helper function to create individual EventParticipantInstance records with the associated event_id and user_id.
- Handled failures in creating participants (logged errors for individual participant creation failures)
- Skipped participant creation logic if there were no invitees.
Closes #73
=> Implemented backend logic for EventParticipant creation and invitee email validation

backend/model/main.js
removed all lines to do with InvitationInstance since its obsolete given Sequelite use in main.js file for database/backend. Resolves npm install import error.
=> Fixing npm install error

backend/controller/controller.js, backend/routes/routes.js
Hello! 
This includes 1) controller.js changes where I added the deleteEventInstance function which will allow the user to delete a event instance and 2) router.js changes. where the backend route added for delete
Close #78
=> Delete: Event Modification #78

backend/controller/controller.js
- In createEvent callback function, I updated the "accepted" field of EventParticipant to "status" in order to reflect the EventParticipantModel
- Refactored organizer_id handling in the createEvent function to use req.user.user_id instead of passing it from the frontend.
Closes #89
=> Updated Event Participant Creation "status" field and organizer_id handling

backend/controller/controller.js, backend/routes/routes.js
Allows user to update the event given event id
Close #88
=> Update controller.js to include Event Modification / Update #88

backend/model/Event.js, frontend/source/components/AppControllerComponent/AppControllerComponent.js, frontend/source/components/EventCreationComponent/EventCreationComponent.js, frontend/source/services/RepositoryRemoteService.js
Integrated the EventCreationComponent on the frontend with the backend POST /events API, enabling event creation functionality. Users can submit event details through the UI, and the data will be sent to the backend using the fetch API.
- Implemented createEvent method in the RepositoryRemoteService that makes a fetch POST request and sends event details to the /events endpoint. The server's response is handled and the appropriate feedback is displayed to the user (success or error messages).
- In RepositoryRemoteService: Added subscription to NewMeeting event to trigger event creation  (createEvent is called)
- In EventCreationComponent: Published a 'NewMeeting' event with the corresponding event details to initiate communication with backend for event creation
- Updated the event_time …
=> Implemented Front-End Integration for EventCreation

backend/model/main.js, frontend/source/components/DashboardComponent/DashboardComponent.js, frontend/source/services/RepositoryRemoteService.js
- Updated `DashboardComponent.js` to correct the data binding issues.
- Modified `RepositoryRemoteService.js` to ensure the correct data is fetched from the backend.
- Adjusted `main.js` in the backend model to fix data processing logic.
- These changes ensure that the dashboard now displays accurate and up-to-date information.
=> Fix frontend dashboard to display the correct data #100:

frontend/source/components/AppControllerComponent/AppControllerComponent.js, frontend/source/components/DashboardComponent/DashboardComponent.js
fix fetch data dashboard #108:
- Added initialization of DashboardComponent on login success in AppControllerComponent.
- Added event listener for Dashboard button to initialize DashboardComponent before switching view.
=> fix fetch data dashboard #108:

backend/controller/controller.js, frontend/source/components/LogInComponent/LogInComponent.css, frontend/source/components/LogInComponent/LogInComponent.js, frontend/source/components/SignUpComponent/SignUpComponent.css, frontend/source/components/SignUpComponent/SignUpComponent.js, frontend/source/eventhub/Events.js, frontend/source/services/RepositoryRemoteService.js
Implement error handling and validation for all authentication form
=> Tan authentication

backend/model/main.js, frontend/source/services/RepositoryRemoteService.js
Fixed bug in RepositoryRemoteService by adding createEvent and getOrganizedEvents methods (they were accidentally deleted in a prior merge)
- Fixed bug resulting in double alert pop-up for successful event creation 
Closes #113
=> Fixed Dashboard and EventCreation bug in RepositoryRemoteService

frontend/source/components/DashboardComponent/DashboardComponent.css, frontend/source/components/DashboardComponent/DashboardComponent.js
- Added CSS styles for edit and delete buttons in `DashboardComponent.css`
- Added edit and delete buttons to the `DashboardComponent` in `DashboardComponent.js`
=> Add edit and delete buttons to the dashboard component #111:

README.md
=> Update instruction for running the project
